### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [kawa5604/fakestagram#1]
Looks like your **README is incomplete** for this assignment. The README helps us to make sure we don't miss any required or optional stories you have completed.

**Make sure all you have completed the following steps to completing your README:**

1. Make sure you have the correct README for this assignment, go to the "Submitting your App Assignment" section in the Assignment Tab for the corresponding unit in the [course portal](https://courses.codepath.org).
2. Please mark all implemented user stories with an `[x]`
3. Add a link to your animated gif walkthrough to your README and make sure it renders (animates) when viewing the README.

Once completed, please push your updates and **submit your assignment again so we can regrade it**.

Still confused about how to properly submit your assignment? Check out the [Submitting Coursework](https://courses.codepath.org/snippets/ios_university/submitting_coursework.md) for detailed instructions.

Whenever you make updates to your project that require re-grading, you need to **re-submit** your project using the submit button on the associated assignment page in the course portal. This will flag your project as “updated” on our end and we know to re-grade.

You should re-submit your assignment anytime you:

- Update a previously incomplete assignment
- Add optional and additional features to an already completed assignment

**Comment by kawa5604** [comment]
FIxed readme

**Comment by codepathreview** [comment]
Congrats on finishing the last individual project! Hopefully, you're beginning to see how you can assemble the things you've learned from the projects to build an app that you design yourself. Here are a few new concepts that we learned from this project that you should reflect on:

- Persisting the logged in user and logging out by programatically instantiating a view controller from the Storyboard and setting the window's root view controller.
- Working with sections and rows in a table view.
- Handling the selection of a row in a table view.
- Adding an array of related Parse objects (comments) to another Parse object (post).
- Integrating MessageInputBar, a custom input accessory.

Check out the [assignment grading page](https://courses.codepath.org/snippets/ios_university/grading) for a breakdown of how submissions are scored.

From here on out there are no more individual assignments as the focus shifts to the final group project. You'll be working over the next several weeks to build your app idea with your team and then finishing the class with a demo day!

If you have any technical questions about the project or concepts covered this week, post a question on our [Discussions Forum](https://discussions.codepath.org) and mark the question as type, "Curiosity". For general questions email us at, <support@codepath.org>. 
/cc @codepathreview
